apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # These are base64 encoded values.
  # username: admin
  mongo-user: YWRtaW4=
  # password: password123
  mongo-password: cGFzc3dvcmQxMjM=